### ISSUE TITLE
Sluggish and slow Settlers with last version

### ISSUE THREAD

**Issue by Vweber73** [vAmigaWeb/vAmigaWeb#105]
Hi,
Something that didn't happen before. I'm using the uat version. 
Loading my Settlers snapshot, I noticed the sound was a bit crappy at times.
Then it became even worse at 28mhz, very slow and sluggish. I tried to put the debug console, see attached.
This may (or not) be linked to the fact that I played with slow ram parameters before. I removed slow ram completely to make sure that the processor was not slowed down, but the problem persists...
Cheers
![Screenshot_20220618-201417_Chrome](https://user-images.githubusercontent.com/92450215/174451491-5fdb0924-9e23-49d5-9723-64819ef6605c.jpg)
![Screenshot_20220618-201249_Chrome](https://user-images.githubusercontent.com/92450215/174451494-cb91b6f2-0ec6-4e2b-967d-8b135b6cec5a.jpg)

**Comment by mithrendal** [comment]
>This may (or not) be linked to the fact that I played with slow ram parameters before. I removed slow ram completely to make sure that the processor was not slowed down, but the problem persists...


there was an issue with slow ram ... which has been resolved 3 days ago in the core ... I just have upgraded the uat with these fixes ...

**Comment by Vweber73** [comment]
Thanks a lot, it seems that it cleared the issue!

**Comment by mithrendal** [comment]
I pushed new release to uat and also to the regular http address ... It solves also a orientation change problem with software renderer...

**Comment by Vweber73** [comment]
Many thanks ! 
Any idea when the mutliple drives and fix joystick features could be available ? 
Cheers

**Comment by Vweber73** [comment]
No, not super important, and those you mentioned are, so please proceed with your plan! :)

Cheers

**Comment by Vweber73** [comment]
I deleted my beta 4 settlers snapshot and recreated it. Once loaded it starts fine, then the sound becomes slow and sluggish again. I have no slow ram this time... Could the issue have been reintroduced?

**Comment by mithrendal** [comment]
Why did you delete it 🫢? You can activate older versions now to run old snapshots. Did you know this?

**Comment by Vweber73** [comment]
Well I have no value for old snapshots, I like to stay current, this was just a shortcut to load the game, nothing important in it...

**Comment by mithrendal** [comment]
Do you still have the old beta version of vAmigaWeb? Try to reactivate it and fire up the settler’s.  Would be great to know whether the slowdown is there too.

**Comment by Vweber73** [comment]
I can try, but here is something new: the problem is hard to reproduce as it happen once I a while, but I found a reproduction scénario: if I change the clock from 28 to 7 the problem stops, and if I put it back to 28 it works fine for a few seconds then the problem starts again! Does it help?

**Comment by Vweber73** [comment]
I have tried the older beta 4 version (2022 07 24 b_uat)  and so far I could not reproduce the issue, even at 28mhz...

**Comment by Vweber73** [comment]
Now I reinstalled the latest beta 5 and I fail to reproduce the problem, even at 28mhz! Strange...

**Comment by mithrendal** [comment]
Doesn’t matter maybe it was just a hiccup. You are a good tester 👍🏻 


please also check the version switching it is brand new 😬i.e. whether the version b4 is different from b5.  You see it when looking at kick3.1 start screen and ecs denise is enabled. B4 is scrambled and b5 not.

**Comment by Vweber73** [comment]
Yes, this is what I did, switching works fine. Even though b5 snapshots are said to be "an older version" when in b4 :)
The thing bugging me right now is the NTSC switch... Doesn't go well and does not save the setting...

**Comment by mithrendal** [comment]
I just tried ... changing the NTSC/PAL setting works ... also restoring from snapshot works well ...

hm ... when started inside web browser (instead of a PWA) the settings are shared between regular and uat version... maybe this confuses you ? On iOS when installed to home screen it is not mixed ... every installation is individual not sharing between different installations...

**Comment by Vweber73** [comment]
Well I have a simple test case on the last b5 uat release, on my Z fold 3:
-Launch uat with kickstart 3.1, no adf no, hdf, you have the welcome screen
-The NTSC switch is not set, I set it
-I reset the amiga
-I return to the settings page, the NTSC switch is off!

**Comment by mithrendal** [comment]
here too ... well done ! you are a testing guru... I look what is going on there

**Comment by mithrendal** [comment]
the core says VIDEO_FORMAT, data=0 after reset which means PAL ...  Then I switch the NTSC setting according to what the core tells me ... hm don't know whether it is an bug or not ... we must ask dirk


@dirkwhoffmann is it intended that the core resets NTSC to PAL on a hard reset ?

**Comment by Vweber73** [comment]
It wouldn't be that much of a problem, if the workbench could detect hot swapping. But see the dedicated thread, workbench showconfig always reports PAL Agnus, even after switching to NTSC mode, and screenmodes always show PAL modes only, whereas with ECS Denise it should actually report both PAL and NTSC modes... So I thought the only way should be to boot in NTSC from scratch, which actually seems impossible, so no way to test! I originally wanted to test superhires in NTSC mode, which is impossible to do in the current setup (at least in workbench).

**Comment by Vweber73** [comment]
Hi,
I got the sluggish sound with 28mhz again, I tried to log it, it seems the number of rendered frames varies a lot, see attached... 
![Screenshot_20220807-174215_Chrome](https://user-images.githubusercontent.com/92450215/183299193-3af17281-5e8c-4f35-9fc6-279b4e5a3c13.jpg)

Cheers

**Comment by mithrendal** [comment]
thanks for reporting @Vweber73 ... interesting finding ... I will try to reproduce ... from your logs I see you run it with PAL and 28Mhz

some more questions

does it run in fastram or chip/slow ram?

when disabling fastram does it happen then too ?

when setting to 7Mhz does it show the problem too ?

**Comment by Vweber73** [comment]
Hi,
I never put slow ram in this test. I used 2mb chip + 2mb fast.
If I put back to 7mhz, no more problem (albeit some small glitches once in a while).
I tried to remove fast ram, which settlers uses for program data. I kept only 2mb chip. So far I could not reproduce the problem.
I just saw a new version was pushed to uat, what does it fix?
Cheers

**Comment by Vweber73** [comment]
Sorry, when I had fast ram I had 8mb of it, not 2. Maybe it was too much?

**Comment by mithrendal** [comment]
recent updates to uat version fixed 

- borderless was often not working correctly ... healed now

- action buttons did not work in the region of the new version toaster ... healed now


also in the regular version


8Mb or 2 MB should not make any difference ... no ? When only enabling chip ram it effectively runs only at 7 Mhz because the chip ram blocks cpu access in favour for denise agnus blitter DMA access... 

I think there seems to be a problem somewhere ... with these test we have too discover the nature and location of the bug... we encircle it and then we will vanish it ;-)

**Comment by mithrendal** [comment]
vAmiga2.1b5, PAL, 28Mhz, 2MBChip+8MBFast

<img width="882" alt="image" src="https://user-images.githubusercontent.com/17108995/183498975-13f63344-63e0-4011-bb8b-c2b75659876d.png">

no sound issues ... all very clear ... constant render times, constant audio buffers


look for reference at the z3 Audio buffers ... audio samples per second vary between 31khz and 58khz ... should be constantly at 48khz ... thats why you hear sound issues ... 

have you tried to cold start your device ? does it have maybe some sort of battery saving mode where it down clocks the CPU of the z3 ? (iPhone does this when battery gets low )...

**Comment by mithrendal** [comment]
Test snap 50 on my aging iPhone 6s (7 years old device)
![218BD60C-E485-4F49-B28C-33FDE09BF08B](https://user-images.githubusercontent.com/17108995/183506407-aa6567c9-7914-4869-b890-a9803de679a3.png)

See audio samples coming in very constantly. Therefore no sound hiccups. Render rates due to 28 Mhz down to 40fps, the 6s phone is not fast enough and skips sometimes a frame. But still very fluently. Everything above 30 is still kind of acceptable. 

If you fire up the snapshot on your iPod touch then it should handle the 28Mhz better than my ancient iPhone.

**Comment by Vweber73** [comment]
Well on my Z fold 3 the issue is not systematic. Most of the time it behaves as you describe. Just once in a while the issue pops up. When it happens my phone is not running on low battery or in any powe saving mode. I don't get it...

**Comment by mithrendal** [comment]
two ways to encircle the problem com to my mind:

###  bad app state
when the problem happens, try to  switch back to 7Mhz ... does it immediately stop then ? 
--->if yes this would point us at to a problem in the app, probably in a bad state. 

###  host device busy with other tasks
when the problem happens, put the app into background and let the z3 run idle for some minutes ... then after 30 minutes or so bring the app back into foreground... does the problem stop then ?
--->if yes this would point to another busy and demanding process on your phone which runs sporadically in background and has an impact on the vAmigaWeb app

**Comment by Vweber73** [comment]
I could already observe that switching back to 7mhz solves the problem.
Next time I will try to observe the second scenario

**Comment by mithrendal** [comment]
>I could already observe that switching back to 7mhz solves the problem.

you are saying the when the sluggish problem happens and then when you switch back to 7Mhz and it stops being sluggish... what happens when you set it again to 28Mhz ?  is it then sluggish again or is it normal ?

**Comment by Vweber73** [comment]
Yes, but not always. Sometimes the problem is fixed for long, sometimes it comes back as soon as you put back in 28mhz mode... Quite hard to reproduce, it comes when it feels like it...

**Comment by mithrendal** [comment]
Ok. When it happens. Try to put it to background and come back after an hour or so and look at the rendertimes. 

I will try and look  on my iPhone too. Every hour or so over this day.

**Comment by mithrendal** [comment]
Ah better way. Do this. 

When it happens. Kill and cold start vAmigaweb. When it then still is sluggish then it is some background task on the z3 and not a bad state in vAmigaWeb. If it isn’t then bad app state is likely. 

Also does it only happen in the settlers ? What about interceptor?

**Comment by Vweber73** [comment]
Not a single problem with Interceptor. Only with settlers, which is one of these few games which try to identify and use every amiga resource (fast ram, better processor...).
I'll try to kill vAmigaWeb, so far working fine, very hard to reproduce...
Cheers

**Comment by Vweber73** [comment]
Btw there is a new uat version today, what does it fix?

**Comment by mithrendal** [comment]
to keep memory usage as low as possible and also to be able to load very big HDFs (hard drive files) I had to enable the emscripten ALLOW_MEMORY_GROWTH feature. If I would go with a static fixed memory modell then even if you wanted only to load a small game like interceptor then it would consume 1GB of memory... The growth feature solves this i.e. I start with a very small memory space e.g. 256MB and when it detects that it is too small then it expands the memory automatically.

The growth feature only worked for the size heap memory. Not for stacksize. The parameter when calling a method from javascript to C++ was all done via the stack. So I had to rework these ones which have very big parameters in order that they use the heap (which can grow). First I only did one call when you drag or select a file i.e. HDF. But yesterday I got a crash when I selected an snapshot which was very big due to HDF inside it. And that one was still done via stack. So I did a complete code cleanup there to use always heap instead of stack for the load function.

>Btw there is a new uat version today, what does it fix?

very big snapshots can be loaded now, because load function uses in all calls now the heap instead of the stack.
