### ISSUE TITLE
Hdf reading error 

### ISSUE THREAD

**Issue by Vweber73** [vAmigaWeb/vAmigaWeb#111]
Trying to load the following workbench hdf (and some others) gives the "offset is out of bounds" error. Then any attempt to load a working hdf or adf gives the same error until the app is restarted. It seems the app is in a currupt state until restart...

http://download.abime.net/classicwb/ClassicWB_68K_v28.zip

**Comment by mithrendal** [comment]
that is because I compiled it with fixed memory size for efficiency reasons and the fixed mem/stackmem is too small

I just changed mem settings to mem=1280MB and stack=256MB  and now this hdf boots ..

pushed it to the uat

**Comment by Vweber73** [comment]
Great, works fine now, many thanks!

**Comment by mithrendal** [comment]
Hm in an older firefox version 78 it gives me this 
`
Uncaught (in promise) RuntimeError: Aborted(CompileError: wasm validation error: at offset 24835: initial memory size too big). Build with -s ASSERTIONS=1 for more info.` 

I think older browser have some sort of a limit ... maybe 1GB ? Unfortunately vAmigaWeb wants for the the system.hdf which counts 209Mb in the provided link exactly 1042MB only a bit above the limit ...  
BTW: why is this hdf soo big? Where is the upper limit ? I set the stacksize to 256Mb now...

Also strange that the stacksize has to be exactly the size of the hdf... maybe I did something wrong here some sort of passing the big file via the stack ? 

```
extern "C" const char* wasm_loadFile(char* name, Uint8 *blob, long len)
{
...
 if (HDFFile::isCompatible(filename)) {
    printf("is hdf\n");
    wrapper->amiga->powerOff();
    HDFFile hdf{blob, len};  
    wrapper->amiga->configure(OPT_HDC_CONNECT,/*hd drive*/ 0, /*enable*/true);
    wrapper->amiga->hd0.init(hdf);
    wrapper->amiga->powerOn();
    return "";
  }
```
@dirkwhoffmann did I maybe screwed it up here in my code above so that it passes the big hdf via stack ?


I just pushed a new version to uat which starts at 512MB heapsize and automatically grows memory when needed. Reducing the memory footprint for smaller disks ...  Unfortunately stacksize can not auto grow...

this wasm auto grow feature is said to have a performance impact ... I will test a little bit and report back here

**Comment by mithrendal** [comment]
UPDATE: auto grow has no noticable impact on performance

Then I think the best is to stick with 512Mb initial memory and allow it to grow when more is needed... the stack unfortunately does not grow ... so I go with a fixed 256Mb stack which means HDFs bigger than 256 will run in the error again...

Maybe @dirkwhoffmann knows more on how to avoid the stack usage when inserting a hdf file. Then when avoiding is possible even larger hdfs would be possible and at the same time we can leave the memory consumption when using no hdf at a minimum...

**Comment by mithrendal** [comment]
We reworked memory and avoided stack usage. Now mem footprint is down to 320 mb. Stack is reduced to 32Mb probably could be set even to a lower value now. But lets stick it to 32 mb for now. 

Memory grows as needed no upper boundary anymore i.e. no boundaries on hdf size anymore
