### ISSUE TITLE
Floppy detection problem

### ISSUE THREAD

**Issue by Vweber73** [vAmigaWeb/vAmigaWeb#113]
Hi,
I was in workbench 3.0 with ecs superhires (lace selected).
I introduced the Interceptor floppy several times, nothing happened, no detection on workbench.
When I reset, both the workbench hdf and the Interceptor adf were properly detected...
Cheers

**Comment by mithrendal** [comment]
found the problem ...

![image](https://user-images.githubusercontent.com/17108995/182473030-5798cb97-888f-46db-8b9c-175322618c73.png)


time_since_start overflows in line 2305 and gets negative somewhen (after several minutes) ... and then it refuses to insert the disk...  this is code from the c64 I think I can remove it then the bug will not be there

this code prevents in the vc64web that the basic load"*",8,1 statement is triggered too early ... I think we don't need this at all in vAmigaWeb because the disk can be inserted very early on ... 

fixed it and pushed to uat

**Comment by mithrendal** [comment]
pushed fix to regular version
