### ISSUE TITLE
Onscreen Keyboard Issue

### ISSUE THREAD

**Issue by aZtOcKdOg** [vAmigaWeb/vAmigaWeb#189]
It seems there is some new erratic behaviour using the onscreen keyboard.
I think it is due to keyboard presses also translating to mouse clicks and shifting the cursor position making it difficult and glitchy to enter text often resulting in almost random effect. But I think it is simply the key also clicks mouse...

**Comment by mithrendal** [comment]
bug confirmed. when mouse touchpad (move|btn/btn)enabled and virtual keyboard visible then key presses on a virtual key also trigger mouse btn press.

**Comment by mithrendal** [comment]
>But I think it is simply the key also clicks mouse...

the touch event has been handled by the virtual key and was then always propagated to the mouse touch pad which clicked a button.

me added a event.stopPropagation() on the element where all rows are inserted. This way only inside the virtual keyboard area event propagation is stopped whereas on the left and right blank areas of the virtual keyboard events are still being sent to the mouse touch pad for the users convenience. So that left right area can still be used as mouse touch pad.

 hope that makes sense


@aZtOcKdOg thanks for reporting

**Comment by aZtOcKdOg** [comment]
Thanks for that info and fast response!

Seems to work as intended again :)
