### ISSUE TITLE
TheCompany_AnotherWorld on whdload.de

### ISSUE THREAD

**Issue by wepl** [vAmigaWeb/vAmigaWeb#254]
https://www.whdload.de/ctros/TheCompany_AnotherWorld.html
this need investigation (last of ctros with problem ATM)
it hangs somehow
I loaded it in vAmiga and it shows that it is waiting for the vertb bit in custom.intreqr, which seems is never set.
I think it is cleared by the int6c whenever set.
But why does this work on real hw and winuae.
Something must behave differently.
![image](https://github.com/user-attachments/assets/64603c96-65e0-4966-9114-8dd9392b49f6)

**Comment by dirkwhoffmann** [comment]
<img width="915" alt="Bildschirmfoto 2024-09-17 um 10 05 59" src="https://github.com/user-attachments/assets/aa4cc334-ec7e-41ec-8c04-bee078565106">

I agree. Seems to be a race condition to me. It depends on when exactly the VERTB bit is set during the execution of the BTST instruction. Interestingly, entering the debugger in vAmiga often makes the demo continue. It seems like suspending / pausing  the emulator brings Agnus and the CPU slightly out of sync. This lets the demo continue, but shouldn't be the case, obviously.

**Comment by mras0** [comment]
Hmm.. I'm sure StringRay had a good reason for installing the generic level 3 handler, but it's a recipe for trouble.

It doesn't work correctly either on my 060 for example (you can hear the music is not going at a constant rate because some vblanks are lost by the main code that also updates music):
https://github.com/user-attachments/assets/5a2dda81-b489-4674-8075-37412d6e702a

The polygon glitching also happens with plain A1200.

I think having this level 3 interrupt (in slave):
```
AckVBI	move.w	#1<<4+1<<5+1<<6,$dff09c
	move.w	#1<<4+1<<5+1<<6,$dff09c
	rte
```

together with this is intro only works if the loop is entered in the right "instruction cycle window"

```
	MOVE.W	#$0020,intreq(A6)
.MainLoop
	BTST.B	#5,intreqr+1(A6)
	BEQ.B	.MainLoop
	MOVE.W	#$0020,intreq(A6)
	...
```

**Comment by wepl** [comment]
thanks for checking, the install should be fixed, I'm asking StingRay

**Comment by dirkwhoffmann** [comment]
Thanks @mras0, for the analysis and checking on the real machine!

I've opened up issue dirkwhoffmann/vamiga#842 on the vAmiga repo, as it relates to the vAmiga core code.

**Comment by dirkwhoffmann** [comment]
Second issue solved (why does the demo continue when entering the debugger in RetroShell?).

Here is the thing: I've entered the debugger by pressing Shift+Return. When RetroShell is open, all key events are intercepted and routed into the shell rather than the emulator. However, the interception check was missing for flag-changing keys such as Shift. As a result, pressing Shift+Return in RetroShell routed the Shift key into the Amiga (in addition to the shell). Pressing a key brings the CPU and Agnus a bit out of sync which lets the BTST instruction recognize VERTB and the demo continues. 

I bet something similar will happen on the real machine. Pressing a key is likely to continue the demo...

**Comment by MK1Roxxor** [comment]
I have updated the patch and removed all default interrupt code and other unused stuff that wasn't needed. It was most likely part of my template code that I didn't remove for some reason. As I created the patch 10 years ago I don't remember the exact details.
Thanks to @mras0, the problem analysis was spot on. The vector logo glitches are caused by SMC in the rotation code, I may update the patch again and remove all SMC from the rotation routine (i.e. I will recode it was that will be much less work than fixing the SMC), don't hold your breath though.

The keyboard interrupt has been added to allow the quitkey check on 68000 machines.

**Comment by mithrendal** [comment]
<img width="791" alt="image" src="https://github.com/user-attachments/assets/f3c25367-dcdf-42fe-a082-da057f6103ac">

😎👌 it is working now.

**Comment by dirkwhoffmann** [comment]
> 😎👌 it is working now.

Win-win. As a side-effect, I've fixed the Retro-shell shift-key bug.

**Comment by MK1Roxxor** [comment]
Indeed, The initial patch only worked by coincidence, not by design. This has now been fixed, as well as an emulator bug. Good outcome I'd say. :)
